sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - os: linux
    - compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libwxgtk3.0-dev libboost-test-dev

script:
  - mkdir build && cd build
  - cmake -DENABLE_TESTS=ON ..
  - make
  - sudo make install
  - sudo ldconfig
  - ctest -VV
